set_property SRC_FILE_INFO {cfile:/mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/ip/template_design_processing_system7_0_0/template_design_processing_system7_0_0.xdc rfile:../../../template_project.srcs/sources_1/bd/template_design/ip/template_design_processing_system7_0_0/template_design_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:template_design_wrapper_i/template_design_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/constrs_1/new/top.xdc rfile:../../../template_project.srcs/constrs_1/new/top.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe10 [get_nets [list {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[0]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[1]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[2]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[3]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[4]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[5]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[6]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[7]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[8]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[9]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[10]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[11]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[12]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[13]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[14]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[15]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[16]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[17]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[18]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[19]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[20]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[21]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[22]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[23]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[24]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[25]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[26]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[27]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[28]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[29]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[30]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_axis_rd_data_count[31]}]]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe11 [get_nets [list {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[0]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[1]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[2]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[3]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[4]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[5]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[6]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[7]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[8]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[9]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[10]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[11]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[12]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[13]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[14]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[15]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[16]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[17]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[18]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[19]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[20]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[21]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[22]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[23]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[24]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[25]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[26]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[27]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[28]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[29]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[30]} {template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TDATA[31]}]]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe26 [get_nets [list template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TLAST]]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe27 [get_nets [list template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TREADY]]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe28 [get_nets [list template_design_wrapper_i/template_design_i/axis_register_slice_0_M_AXIS_TVALID]]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe29 [get_nets [list template_design_wrapper_i/template_design_i/axis_register_slice_0_s_axis_tready]]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe30 [get_nets [list template_design_wrapper_i/template_design_i/c_addsub_0_C_OUT]]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe63 [get_nets [list template_design_wrapper_i/template_design_i/util_vector_logic_0_Res]]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe64 [get_nets [list template_design_wrapper_i/template_design_i/util_vector_logic_1_Res]]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[0]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[1]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[2]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[3]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[4]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[5]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[6]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[7]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[8]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[9]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[10]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[11]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[12]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[13]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[14]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[15]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[16]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[17]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[18]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[19]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[20]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[21]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[22]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[23]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[24]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[25]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[26]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[27]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[28]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[29]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[30]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[31]}]]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe64 [get_nets [list template_design_wrapper_i/template_design_i/s_axis_1_TLAST]]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe65 [get_nets [list template_design_wrapper_i/template_design_i/s_axis_1_TREADY]]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe66 [get_nets [list template_design_wrapper_i/template_design_i/s_axis_1_TVALID]]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe27 [get_nets [list template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_C_OUT]]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[0]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[1]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[2]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[3]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[4]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[5]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[6]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[7]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[8]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[9]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[10]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[11]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[12]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[13]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[14]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[15]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[16]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[17]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[18]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[19]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[20]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[21]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[22]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[23]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[24]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[25]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[26]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[27]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[28]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[29]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[30]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TDATA[31]}]]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe28 [get_nets [list template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TLAST]]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe29 [get_nets [list template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TREADY]]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe30 [get_nets [list template_design_wrapper_i/template_design_i/dma_stuff_0/Conn3_TVALID]]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0_0 ila
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/clk]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/clk [get_nets [list template_design_wrapper_i/template_design_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 26 [get_debug_ports u_ila_0_0/probe0]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe0 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[2]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[3]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[4]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[5]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[6]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[7]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[8]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[9]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[10]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[11]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[12]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[13]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[14]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[15]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[16]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[17]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[18]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[19]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[20]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[21]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[22]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[23]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[24]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_len[25]}]]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 26 [get_debug_ports u_ila_0_0/probe1]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe1 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[2]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[3]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[4]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[5]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[6]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[7]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[8]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[9]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[10]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[11]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[12]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[13]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[14]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[15]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[16]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[17]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[18]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[19]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[20]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[21]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[22]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[23]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[24]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_len[25]}]]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0_0/probe2]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe2 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WSTRB[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WSTRB[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WSTRB[2]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WSTRB[3]}]]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0_0/probe3]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe3 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[2]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[3]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[4]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[5]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[6]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[7]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[8]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[9]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[10]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[11]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[12]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[13]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[14]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[15]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[16]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[17]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[18]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[19]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[20]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[21]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[22]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[23]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[24]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[25]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[26]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[27]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[28]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[29]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[30]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RDATA[31]}]]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0_0/probe4]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe4 [get_nets [list {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[0]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[1]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[2]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[3]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[4]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[5]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[6]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[7]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[8]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[9]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[10]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[11]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[12]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[13]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[14]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[15]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[16]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[17]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[18]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[19]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[20]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[21]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[22]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[23]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[24]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[25]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[26]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[27]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[28]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[29]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[30]} {template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TDATA[31]}]]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0_0/probe5]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe5 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWSIZE[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWSIZE[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWSIZE[2]}]]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0_0/probe6]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe6 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_BRESP[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_BRESP[1]}]]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0_0/probe7]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe7 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[2]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[3]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[4]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[5]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[6]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[7]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[8]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[9]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[10]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[11]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[12]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[13]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[14]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[15]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[16]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[17]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[18]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[19]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[20]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[21]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[22]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[23]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[24]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[25]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[26]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[27]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[28]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[29]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[30]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARADDR[31]}]]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0_0/probe8]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe8 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[2]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[3]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[4]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[5]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[6]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[7]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[8]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[9]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[10]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[11]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[12]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[13]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[14]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[15]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[16]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[17]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[18]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[19]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[20]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[21]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[22]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[23]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[24]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[25]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[26]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[27]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[28]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[29]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[30]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_addr[31]}]]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0_0/probe9]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe9 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARCACHE[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARCACHE[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARCACHE[2]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARCACHE[3]}]]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0_0/probe10]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe10 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[2]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[3]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[4]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[5]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[6]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[7]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[8]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[9]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[10]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[11]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[12]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[13]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[14]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[15]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[16]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[17]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[18]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[19]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[20]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[21]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[22]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[23]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[24]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[25]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[26]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[27]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[28]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[29]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[30]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_addr[31]}]]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0_0/probe11]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe11 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARLEN[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARLEN[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARLEN[2]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARLEN[3]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARLEN[4]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARLEN[5]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARLEN[6]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARLEN[7]}]]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0_0/probe12]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe12 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARBURST[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARBURST[1]}]]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0_0/probe13]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe13 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RRESP[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RRESP[1]}]]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0_0/probe14]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe14 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[2]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[3]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[4]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[5]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[6]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[7]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[8]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[9]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[10]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[11]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[12]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[13]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[14]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[15]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[16]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[17]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[18]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[19]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[20]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[21]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[22]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[23]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[24]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[25]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[26]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[27]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[28]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[29]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[30]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WDATA[31]}]]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0_0/probe15]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe15 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWBURST[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWBURST[1]}]]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0_0/probe16]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe16 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWCACHE[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWCACHE[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWCACHE[2]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWCACHE[3]}]]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0_0/probe17]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe17 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWLEN[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWLEN[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWLEN[2]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWLEN[3]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWLEN[4]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWLEN[5]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWLEN[6]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWLEN[7]}]]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0_0/probe18]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe18 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[2]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[3]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[4]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[5]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[6]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[7]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[8]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[9]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[10]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[11]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[12]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[13]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[14]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[15]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[16]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[17]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[18]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[19]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[20]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[21]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[22]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[23]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[24]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[25]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[26]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[27]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[28]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[29]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[30]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWADDR[31]}]]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0_0/probe19]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe19 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWQOS[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWQOS[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWQOS[2]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWQOS[3]}]]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0_0/probe20]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe20 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWPROT[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWPROT[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWPROT[2]}]]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0_0/probe21]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe21 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARPROT[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARPROT[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARPROT[2]}]]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0_0/probe22]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe22 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARSIZE[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARSIZE[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARSIZE[2]}]]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0_0/probe23]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe23 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARQOS[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARQOS[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARQOS[2]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARQOS[3]}]]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0_0/probe24]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe24 [get_nets [list {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[0]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[1]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[2]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[3]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[4]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[5]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[6]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[7]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[8]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[9]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[10]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[11]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[12]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[13]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[14]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[15]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[16]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[17]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[18]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[19]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[20]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[21]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[22]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[23]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[24]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[25]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[26]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[27]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[28]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[29]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[30]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[31]}]]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0_0/probe25]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe25 [get_nets [list {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[0]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[1]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[2]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[3]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[4]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[5]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[6]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[7]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[8]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[9]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[10]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[11]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[12]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[13]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[14]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[15]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[16]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[17]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[18]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[19]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[20]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[21]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[22]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[23]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[24]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[25]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[26]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[27]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[28]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[29]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[30]} {template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_0_axis_rd_data_count[31]}]]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0_0/probe26]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe26 [get_nets [list {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[0]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[1]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[2]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[3]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[4]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[5]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[6]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[7]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[8]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[9]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[10]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[11]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[12]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[13]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[14]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[15]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[16]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[17]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[18]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[19]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[20]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[21]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[22]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[23]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[24]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[25]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[26]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[27]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[28]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[29]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[30]} {template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TDATA[31]}]]
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0_0/probe27]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe27 [get_nets [list {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[0]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[1]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[2]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[3]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[4]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[5]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[6]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[7]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[8]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[9]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[10]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[11]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[12]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[13]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[14]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[15]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[16]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[17]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[18]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[19]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[20]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[21]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[22]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[23]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[24]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[25]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[26]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[27]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[28]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[29]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[30]} {template_design_wrapper_i/template_design_i/dma_stuff_0/c_addsub_0_S[31]}]]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe28]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe28 [get_nets [list template_design_wrapper_i/template_design_i/dma_stuff_0/axis_data_fifo_1_m_axis_tvalid]]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe29]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe29 [get_nets [list template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TLAST]]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe30]
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe30 [get_nets [list template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TREADY]]
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe31]
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe31 [get_nets [list template_design_wrapper_i/template_design_i/dma_stuff_0/Conn1_TVALID]]
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe32]
set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe32 [get_nets [list template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TLAST]]
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe33]
set_property src_info {type:XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe33 [get_nets [list template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TREADY]]
set_property src_info {type:XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe34]
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe34 [get_nets [list template_design_wrapper_i/template_design_i/dma_stuff_0_M_AXIS1_TVALID]]
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe35]
set_property src_info {type:XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe35 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARID]]
set_property src_info {type:XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe36]
set_property src_info {type:XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe36 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARLOCK]]
set_property src_info {type:XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe37]
set_property src_info {type:XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe37 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARREADY]]
set_property src_info {type:XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe38]
set_property src_info {type:XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe38 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARUSER]]
set_property src_info {type:XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe39]
set_property src_info {type:XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe39 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_ARVALID]]
set_property src_info {type:XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe40]
set_property src_info {type:XDC file:2 line:156 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe40 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWID]]
set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe41]
set_property src_info {type:XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe41 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWLOCK]]
set_property src_info {type:XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe42]
set_property src_info {type:XDC file:2 line:162 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe42 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWREADY]]
set_property src_info {type:XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe43]
set_property src_info {type:XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe43 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWUSER]]
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe44]
set_property src_info {type:XDC file:2 line:168 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe44 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_AWVALID]]
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe45]
set_property src_info {type:XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe45 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_BID]]
set_property src_info {type:XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe46]
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe46 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_BREADY]]
set_property src_info {type:XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe47]
set_property src_info {type:XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe47 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_BVALID]]
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe48]
set_property src_info {type:XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe48 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RID]]
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe49]
set_property src_info {type:XDC file:2 line:183 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe49 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RLAST]]
set_property src_info {type:XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe50]
set_property src_info {type:XDC file:2 line:186 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe50 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RREADY]]
set_property src_info {type:XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe51]
set_property src_info {type:XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe51 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RUSER]]
set_property src_info {type:XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe52]
set_property src_info {type:XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe52 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_RVALID]]
set_property src_info {type:XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe53]
set_property src_info {type:XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe53 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WLAST]]
set_property src_info {type:XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe54]
set_property src_info {type:XDC file:2 line:198 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe54 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WREADY]]
set_property src_info {type:XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe55]
set_property src_info {type:XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe55 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WUSER]]
set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe56]
set_property src_info {type:XDC file:2 line:204 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe56 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_0_M_AXI_WVALID]]
set_property src_info {type:XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe57]
set_property src_info {type:XDC file:2 line:207 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe57 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_compl]]
set_property src_info {type:XDC file:2 line:208 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe58]
set_property src_info {type:XDC file:2 line:210 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe58 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_ready]]
set_property src_info {type:XDC file:2 line:211 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe59]
set_property src_info {type:XDC file:2 line:213 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe59 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_r_valid]]
set_property src_info {type:XDC file:2 line:214 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe60]
set_property src_info {type:XDC file:2 line:216 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe60 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_rst]]
set_property src_info {type:XDC file:2 line:217 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe61]
set_property src_info {type:XDC file:2 line:219 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe61 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_compl]]
set_property src_info {type:XDC file:2 line:220 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe62]
set_property src_info {type:XDC file:2 line:222 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe62 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_ready]]
set_property src_info {type:XDC file:2 line:223 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe63]
set_property src_info {type:XDC file:2 line:225 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe63 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_dma_control_w_valid]]
set_property src_info {type:XDC file:2 line:226 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe64]
set_property src_info {type:XDC file:2 line:228 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe64 [get_nets [list template_design_wrapper_i/template_design_i/s_axis_1_TLAST]]
set_property src_info {type:XDC file:2 line:229 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe65]
set_property src_info {type:XDC file:2 line:231 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe65 [get_nets [list template_design_wrapper_i/template_design_i/s_axis_1_TREADY]]
set_property src_info {type:XDC file:2 line:232 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe66]
set_property src_info {type:XDC file:2 line:234 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe66 [get_nets [list template_design_wrapper_i/template_design_i/s_axis_1_TVALID]]
set_property src_info {type:XDC file:2 line:235 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe67]
set_property src_info {type:XDC file:2 line:237 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe67 [get_nets [list template_design_wrapper_i/template_design_i/dma_stuff_0/util_vector_logic_1_Res]]
set_property src_info {type:XDC file:2 line:238 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe68]
set_property src_info {type:XDC file:2 line:240 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe68 [get_nets [list template_design_wrapper_i/template_design_i/dma_stuff_0/util_vector_logic_3_Res]]
set_property src_info {type:XDC file:2 line:241 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:2 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe69]
set_property src_info {type:XDC file:2 line:243 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe69 [get_nets [list template_design_wrapper_i/template_design_i/dma_stuff_0/xlslice_0_Dout]]
set_property src_info {type:XDC file:2 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:247 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets CLK]
