set_property SRC_FILE_INFO {cfile:/mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/ip/template_design_processing_system7_0_0/template_design_processing_system7_0_0.xdc rfile:../../../template_project.srcs/sources_1/bd/template_design/ip/template_design_processing_system7_0_0/template_design_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:template_design_wrapper_i/template_design_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/constrs_1/new/top.xdc rfile:../../../template_project.srcs/constrs_1/new/top.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list template_design_wrapper_i/template_design_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[0]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[1]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[2]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[3]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[4]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[5]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[6]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[7]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[8]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[9]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[10]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[11]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[12]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[13]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[14]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[15]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[16]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[17]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[18]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[19]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[20]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[21]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[22]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[23]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[24]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[25]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[26]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[27]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[28]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[29]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[30]} {template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TDATA[31]}]]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[0]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[1]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[2]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[3]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[4]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[5]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[6]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[7]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[8]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[9]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[10]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[11]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[12]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[13]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[14]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[15]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[16]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[17]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[18]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[19]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[20]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[21]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[22]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[23]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[24]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[25]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[26]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[27]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[28]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[29]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[30]} {template_design_wrapper_i/template_design_i/s_axis_1_TDATA[31]}]]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[0]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[1]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[2]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[3]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[4]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[5]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[6]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[7]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[8]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[9]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[10]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[11]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[12]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[13]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[14]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[15]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[16]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[17]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[18]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[19]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[20]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[21]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[22]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[23]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[24]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[25]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[26]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[27]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[28]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[29]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[30]} {template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TDATA[31]}]]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TLAST]]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TREADY]]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list template_design_wrapper_i/template_design_i/axis_data_fifo_0_M_AXIS_TVALID]]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TLAST]]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TREADY]]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list template_design_wrapper_i/template_design_i/MINIMAL_DMA_CONTROL_0_m_axis_TVALID]]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list template_design_wrapper_i/template_design_i/s_axis_1_TLAST]]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list template_design_wrapper_i/template_design_i/s_axis_1_TREADY]]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list template_design_wrapper_i/template_design_i/s_axis_1_TVALID]]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets CLK]
