# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/template_design/template_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design || ORIG_REF_NAME==template_design}]

# IP: bd/template_design/ip/template_design_processing_system7_0_0/template_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_processing_system7_0_0 || ORIG_REF_NAME==template_design_processing_system7_0_0}]

# IP: bd/template_design/ip/template_design_processing_system7_0_axi_periph_0/template_design_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==template_design_processing_system7_0_axi_periph_0}]

# IP: bd/template_design/ip/template_design_rst_processing_system7_0_102M_0/template_design_rst_processing_system7_0_102M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_rst_processing_system7_0_102M_0 || ORIG_REF_NAME==template_design_rst_processing_system7_0_102M_0}]

# IP: bd/template_design/ip/template_design_axi_mem_intercon_0/template_design_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_axi_mem_intercon_0 || ORIG_REF_NAME==template_design_axi_mem_intercon_0}]

# IP: bd/template_design/ip/template_design_MINIMAL_DMA_0_0/template_design_MINIMAL_DMA_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_MINIMAL_DMA_0_0 || ORIG_REF_NAME==template_design_MINIMAL_DMA_0_0}]

# IP: bd/template_design/ip/template_design_MINIMAL_DMA_CONTROL_0_0/template_design_MINIMAL_DMA_CONTROL_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_MINIMAL_DMA_CONTROL_0_0 || ORIG_REF_NAME==template_design_MINIMAL_DMA_CONTROL_0_0}]

# IP: bd/template_design/ip/template_design_axis_data_fifo_0_0/template_design_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_axis_data_fifo_0_0 || ORIG_REF_NAME==template_design_axis_data_fifo_0_0}]

# IP: bd/template_design/ip/template_design_util_vector_logic_0_0/template_design_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_util_vector_logic_0_0 || ORIG_REF_NAME==template_design_util_vector_logic_0_0}]

# IP: bd/template_design/ip/template_design_ila_0_0/template_design_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_ila_0_0 || ORIG_REF_NAME==template_design_ila_0_0}]

# IP: bd/template_design/ip/template_design_axis_data_fifo_1_0/template_design_axis_data_fifo_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_axis_data_fifo_1_0 || ORIG_REF_NAME==template_design_axis_data_fifo_1_0}]

# IP: bd/template_design/ip/template_design_c_addsub_0_0/template_design_c_addsub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_c_addsub_0_0 || ORIG_REF_NAME==template_design_c_addsub_0_0}]

# IP: bd/template_design/ip/template_design_axis_register_slice_0_0/template_design_axis_register_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_axis_register_slice_0_0 || ORIG_REF_NAME==template_design_axis_register_slice_0_0}]

# IP: bd/template_design/ip/template_design_util_vector_logic_1_0/template_design_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_util_vector_logic_1_0 || ORIG_REF_NAME==template_design_util_vector_logic_1_0}]

# IP: bd/template_design/ip/template_design_auto_pc_0/template_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_auto_pc_0 || ORIG_REF_NAME==template_design_auto_pc_0}]

# IP: bd/template_design/ip/template_design_auto_pc_1/template_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_auto_pc_1 || ORIG_REF_NAME==template_design_auto_pc_1}]

# XDC: bd/template_design/ip/template_design_processing_system7_0_0/template_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==template_design_processing_system7_0_0 || ORIG_REF_NAME==template_design_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/template_design/ip/template_design_rst_processing_system7_0_102M_0/template_design_rst_processing_system7_0_102M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_rst_processing_system7_0_102M_0 || ORIG_REF_NAME==template_design_rst_processing_system7_0_102M_0}]

# XDC: bd/template_design/ip/template_design_rst_processing_system7_0_102M_0/template_design_rst_processing_system7_0_102M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_rst_processing_system7_0_102M_0 || ORIG_REF_NAME==template_design_rst_processing_system7_0_102M_0}]

# XDC: bd/template_design/ip/template_design_rst_processing_system7_0_102M_0/template_design_rst_processing_system7_0_102M_0_ooc.xdc

# XDC: bd/template_design/ip/template_design_axis_data_fifo_0_0/template_design_axis_data_fifo_0_0_ooc.xdc

# XDC: bd/template_design/ip/template_design_axis_data_fifo_0_0/template_design_axis_data_fifo_0_0/template_design_axis_data_fifo_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==template_design_axis_data_fifo_0_0 || ORIG_REF_NAME==template_design_axis_data_fifo_0_0}] {/inst }]/inst ]]

# XDC: bd/template_design/ip/template_design_ila_0_0/ila_v5_1/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==template_design_ila_0_0 || ORIG_REF_NAME==template_design_ila_0_0}]

# XDC: bd/template_design/ip/template_design_ila_0_0/template_design_ila_0_0_ooc.xdc

# XDC: bd/template_design/ip/template_design_axis_data_fifo_1_0/template_design_axis_data_fifo_1_0_ooc.xdc

# XDC: bd/template_design/ip/template_design_axis_data_fifo_1_0/template_design_axis_data_fifo_1_0/template_design_axis_data_fifo_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==template_design_axis_data_fifo_1_0 || ORIG_REF_NAME==template_design_axis_data_fifo_1_0}] {/inst }]/inst ]]

# XDC: bd/template_design/ip/template_design_c_addsub_0_0/template_design_c_addsub_0_0_ooc.xdc

# XDC: bd/template_design/ip/template_design_axis_register_slice_0_0/template_design_axis_register_slice_0_0_ooc.xdc

# XDC: bd/template_design/ip/template_design_auto_pc_0/template_design_auto_pc_0_ooc.xdc

# XDC: bd/template_design/ip/template_design_auto_pc_1/template_design_auto_pc_1_ooc.xdc

# XDC: bd/template_design/template_design_ooc.xdc
