# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.cache/wt [current_project]
set_property parent.project_path /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /mnt/studproj/ebensberger/vhdl-sejits/src/vivado [current_project]
add_files /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/template_design.bd
set_property used_in_implementation false [get_files -all /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/ip/template_design_processing_system7_0_0/template_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/ip/template_design_rst_processing_system7_0_102M_0/template_design_rst_processing_system7_0_102M_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/ip/template_design_rst_processing_system7_0_102M_0/template_design_rst_processing_system7_0_102M_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/ip/template_design_rst_processing_system7_0_102M_0/template_design_rst_processing_system7_0_102M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/ip/template_design_axis_data_fifo_0_0/template_design_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/ip/template_design_axis_data_fifo_0_0/template_design_axis_data_fifo_0_0/template_design_axis_data_fifo_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/ip/template_design_axis_data_fifo_1_0/template_design_axis_data_fifo_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/ip/template_design_axis_data_fifo_1_0/template_design_axis_data_fifo_1_0/template_design_axis_data_fifo_1_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/ip/template_design_c_addsub_0_0/template_design_c_addsub_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/ip/template_design_axis_register_slice_0_0/template_design_axis_register_slice_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/ip/template_design_auto_pc_0/template_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/ip/template_design_auto_pc_1/template_design_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/template_design_ooc.xdc]
set_property is_locked true [get_files /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/template_design.bd]

read_vhdl -library xil_defaultlib {
  /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/new/logic_dff.vhd
  /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/new/the_filter_package.vhd
  /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/new/AddBB.vhd
  /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/new/generated.vhd
  /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/bd/template_design/hdl/template_design_wrapper.vhd
  /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/new/accel_wrapper.vhd
  /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/sources_1/new/top.vhd
}
read_xdc /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files /mnt/studproj/ebensberger/vhdl-sejits/src/vivado/template_project/template_project.srcs/constrs_1/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top top -part xc7z020clg484-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
